study_name = 'POGS'
bids_root = "./bids_data"
task = 'POGS'
ch_types = ['mag', 'grad']
find_flat_channels_meg = True
find_noisy_channels_meg = True
use_maxwell_filter = True
mf_cal_fname = "./meg_conf/sss_cal_nsp_2017.dat"
mf_ctc_fname = "./meg_conf/ct_sparse_nsp_2017.fif"
l_freq = .1
resample_sfreq = 500
conditions = ["reference", "outlier", "square/reference", "random/reference"]
epochs_tmin = -0.1
epochs_tmax = 1.1
baseline = None
contrasts = [("reference", "outlier")]
spatial_filter = "ica"
ica_n_components = None
ica_ctps_ecg_threshold = 0.09
ica_eog_threshold = 3.
reject_tmin = 0.
reject_tmax = .8
run_source_estimation = True
# run_source_estimation = False
process_er = True
noise_cov = "emptyroom"
N_JOBS = 1

on_error = "debug"
